// Builds the audit report as a printable page; the browser's "Save as PDF" turns it into a PDF.
// No PDF library is needed, matching how invoices are already exported.
import { computeMetrics } from './metrics';
import { AUDIT_ACTIONS } from './audit';
import { ROLE_LABELS } from '../security/roles';

const esc = (v) => String(v ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const money = (n) => `₹${Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;
const day = (ms) => new Date(ms).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
const stamp = (ms) => new Date(ms).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
const summarise = (v) => (v == null ? '' : typeof v === 'object' ? Object.entries(v).map(([k, x]) => `${k}: ${Array.isArray(x) ? x.join(', ') : typeof x === 'object' && x ? JSON.stringify(x) : x}`).join('; ') : String(v));

/** logs: audit records already filtered to the period; data/insights: from useOrgInsights */
export function buildReportHtml({ orgName, generatedBy, from, to, logs, data, insights }) {
  const m = computeMetrics(data, insights, { from, to });
  const k = m.kpis;
  const highRisk = Object.values(insights.risks).filter(r => r.level === 'HIGH');
  const alerts = m.filtered.alerts;
  const anomalies = m.filtered.bills.filter(b => b.analysis && b.analysis.level !== 'clear');
  const approvals = logs.filter(l => ['INVOICE_APPROVED', 'INVOICE_REJECTED', 'INVOICE_FULLY_APPROVED', 'RISK_REVIEW_DECISION', 'PAYMENT_COMPLETED'].includes(l.action));

  const table = (head, rows) => rows.length
    ? `<table><thead><tr>${head.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`
    : '<p class="none">None in this period.</p>';

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Tether audit report ${esc(day(from))} – ${esc(day(to))}</title>
<style>
  body { font-family: Arial, Helvetica, sans-serif; color: #16181d; margin: 36px; font-size: 12px; }
  h1 { font-size: 13px; letter-spacing: .2em; margin: 0; color: #2563eb; }
  h2 { font-size: 20px; margin: 4px 0 2px; }
  h3 { font-size: 14px; margin: 26px 0 8px; border-bottom: 1px solid #e4e6eb; padding-bottom: 4px; }
  .meta { color: #5f6570; margin-bottom: 18px; }
  .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }
  .kpi { border: 1px solid #e4e6eb; border-radius: 8px; padding: 8px 10px; }
  .kpi b { display: block; font-size: 16px; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; margin-top: 4px; }
  th, td { text-align: left; padding: 5px 6px; border-bottom: 1px solid #eef0f3; vertical-align: top; }
  th { color: #5f6570; font-weight: 600; font-size: 11px; }
  .none { color: #8b909a; }
  .note { color: #5f6570; font-size: 11px; margin-top: 24px; }
  @media print { body { margin: 14mm; } h3 { break-after: avoid; } tr { break-inside: avoid; } }
</style></head><body>
<h1>TETHER</h1>
<h2>Secure Procurement Audit Report</h2>
<div class="meta">${esc(orgName)} · Period: ${esc(day(from))} – ${esc(day(to))} · Generated by ${esc(generatedBy)} on ${esc(stamp(Date.now()))}</div>

<h3>Procurement summary</h3>
<div class="grid">
  <div class="kpi">Total procurement (contracted)<b>${money(k.procurementValue)}</b></div>
  <div class="kpi">Paid in period<b>${money(k.totalSpend)}</b></div>
  <div class="kpi">Potential leakage<b>${money(k.leakageDetected)}</b></div>
  <div class="kpi">Leakage prevented<b>${money(k.leakagePrevented)}</b></div>
  <div class="kpi">Tenders<b>${k.totalTenders}</b></div>
  <div class="kpi">Contracts<b>${k.contracts}</b></div>
  <div class="kpi">Invoices<b>${k.invoices}</b></div>
  <div class="kpi">Flagged invoices<b>${k.invoicesFlagged}</b></div>
</div>

<h3>Supplier summary</h3>
<div class="grid">
  <div class="kpi">Suppliers<b>${k.suppliers}</b></div>
  <div class="kpi">High-risk suppliers<b>${highRisk.length}</b></div>
  <div class="kpi">Average supplier risk<b>${k.averageSupplierRisk}/100</b></div>
  <div class="kpi">Open risk alerts<b>${alerts.length}</b></div>
</div>
${table(['Supplier', 'Risk score', 'Level', 'Main reasons'], Object.values(insights.risks).sort((a, b) => b.score - a.score)
    .map(r => [r.supplier.companyName || r.supplier.email, `${r.score}/100`, r.level, r.factors.map(f => f.label).join('; ') || '—']))}

<h3>Suspicious activities</h3>
${table(['Level', 'Pattern', 'Why'], alerts.map(a => [a.level, a.title, a.reasons.join(' ')]))}

<h3>Invoice anomalies</h3>
${table(['Invoice', 'Supplier', 'Amount', 'AI decision', 'Flags'], anomalies.map(b => [
    `#${b.invoiceNumber || b.id.slice(0, 8).toUpperCase()}`, data.suppliers[b.supplierId]?.companyName || '—', money(b.amount),
    `${b.analysis.level} (${b.analysis.riskScore}/100)`, b.analysis.flags.map(f => f.title).join('; ')]))}

<h3>Approval history</h3>
${table(['When', 'Who', 'Role', 'Action', 'Invoice', 'Reason'], approvals.map(l => [
    stamp(l.ms), l.userName, ROLE_LABELS[l.userRole] || l.userRole, AUDIT_ACTIONS[l.action] || l.action, l.entityLabel, l.reason || '']))}

<h3>Audit events (${logs.length})</h3>
${table(['When', 'User', 'Role', 'Action', 'Entity', 'Details'], logs.map(l => [
    stamp(l.ms), l.userName, ROLE_LABELS[l.userRole] || l.userRole, AUDIT_ACTIONS[l.action] || l.action,
    `${l.entityType || ''} ${l.entityLabel || ''}`.trim(), [summarise(l.next), l.reason ? `Reason: ${l.reason}` : ''].filter(Boolean).join(' · ')]))}

<p class="note">Figures are calculated from Tether records for the period shown. Suspicious patterns are indicators for review, not findings of fraud.
Supplier verification confirms the validity and consistency of submitted information; it does not independently authenticate government or banking records.</p>
</body></html>`;
}

export function openPrintable(html) {
  const w = window.open('', '_blank');
  if (!w) throw new Error('Your browser blocked the report window. Allow pop-ups for this site and try again.');
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}
