import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { db } from '../firebase';
import { collection, query, where, onSnapshot, doc, updateDoc } from 'firebase/firestore';
import { Search, Download } from 'lucide-react';

export default function MyOrders() {
  const { currentUser } = useAuth();
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (!currentUser) return;

    const q = query(
      collection(db, 'bills'),
      where('consumerId', '==', currentUser.uid)
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const fetched = [];
      snapshot.forEach((docSnap) => {
        fetched.push({ id: docSnap.id, ...docSnap.data() });
      });
      // Sort newest first
      fetched.sort((a, b) => b.createdAt?.toMillis() - a.createdAt?.toMillis());
      setBills(fetched);
      setLoading(false);
    }, (error) => {
      console.error("Error fetching bills:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [currentUser]);

  const handlePay = async (billId) => {
    try {
      const billRef = doc(db, 'bills', billId);
      await updateDoc(billRef, { status: 'paid' });
    } catch (err) {
      console.error("Payment failed:", err);
      alert("Payment failed: " + err.message);
    }
  };

  const downloadBillPDF = (bill) => {
    const displayId = bill.id.substring(0, 8).toUpperCase();
    const dateStr = bill.createdAt ? new Date(bill.createdAt.toMillis()).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : 'N/A';
    const isPaid = bill.status === 'paid';

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8" />
        <title>Bill #${displayId}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 48px; color: #111; max-width: 560px; margin: 0 auto; }
          h1 { font-size: 1.75rem; margin-bottom: 0.25rem; }
          .sub { color: #666; font-size: 0.875rem; margin-bottom: 2rem; }
          table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
          td { padding: 0.75rem 0; border-bottom: 1px solid #eee; }
          td:last-child { text-align: right; font-weight: 600; }
          .total td { border-top: 2px solid #111; border-bottom: none; font-weight: 700; font-size: 1.125rem; }
          .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.75rem; font-weight: 700; background: ${isPaid ? '#e6f4ea' : '#fce8e6'}; color: ${isPaid ? '#137333' : '#c5221f'}; }
          .footer { margin-top: 3rem; color: #999; font-size: 0.75rem; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Tether</h1>
        <p class="sub">Tax Invoice / Bill</p>
        <hr />
        <table>
          <tr><td>Bill ID</td><td>#${displayId}</td></tr>
          <tr><td>Product</td><td>${bill.productName}</td></tr>
          <tr><td>Description</td><td>${bill.description}</td></tr>
          <tr><td>Date</td><td>${dateStr}</td></tr>
          <tr><td>Status</td><td><span class="badge">${isPaid ? 'PAID' : 'UNPAID'}</span></td></tr>
          <tr class="total"><td>Total Amount</td><td>₹${Number(bill.amount).toFixed(2)}</td></tr>
        </table>
        <p class="footer">Generated by Tether Warehouse Management &bull; ${new Date().toLocaleDateString()}</p>
      </body>
      </html>
    `;

    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); }, 400);
  };

  if (loading) {
    return (
      <div className="page-container" style={{ alignItems: 'center', paddingTop: '4rem' }}>
        <span className="spinner" style={{ width: '2rem', height: '2rem' }}></span>
      </div>
    );
  }

  // Filter bills based on search query (by ID, product name, or description)
  const filteredBills = bills.filter(bill => {
    if (!searchQuery.trim()) return true;
    const term = searchQuery.replace('#', '').trim().toUpperCase();
    const displayId = bill.id.substring(0, 8).toUpperCase();
    return (
      displayId.includes(term) ||
      bill.productName?.toUpperCase().includes(term) ||
      bill.description?.toUpperCase().includes(term)
    );
  });

  return (
    <div className="page-container">
      <div className="page-header" style={{ marginBottom: '1.5rem' }}>
        <h2 style={{ fontSize: '2rem', fontWeight: '600' }}>My Orders & Billing</h2>
        <p style={{ color: 'var(--text-secondary)', marginTop: '0.5rem' }}>
          Review your purchase requests and pay incoming bills from suppliers.
        </p>
      </div>

      {/* Search bar */}
      <div style={{ position: 'relative', marginBottom: '1.5rem', width: '100%' }}>
        <Search size={18} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-secondary)', pointerEvents: 'none' }} />
        <input
          type="text"
          className="form-input"
          placeholder="Search by ID, product or description…"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          style={{ paddingLeft: '2.75rem', width: '100%', boxSizing: 'border-box' }}
        />
      </div>

      {bills.length === 0 ? (
        <div style={{ padding: '3rem', textAlign: 'center', border: '1px dashed var(--border-color)', color: 'var(--text-secondary)' }}>
          You have no pending bills or orders.
        </div>
      ) : filteredBills.length === 0 ? (
        <div style={{ padding: '3rem', textAlign: 'center', border: '1px dashed var(--border-color)', color: 'var(--text-secondary)' }}>
          No results found for "{searchQuery}".
        </div>
      ) : (
        <div style={{ overflowX: 'auto', border: '1px solid var(--border-color)' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ backgroundColor: 'var(--surface-color)', borderBottom: '2px solid var(--border-color)' }}>
                <th style={{ padding: '1rem' }}>ID</th>
                <th style={{ padding: '1rem' }}>Product</th>
                <th style={{ padding: '1rem' }}>Description</th>
                <th style={{ padding: '1rem' }}>Date</th>
                <th style={{ padding: '1rem', textAlign: 'right' }}>Amount (₹)</th>
                <th style={{ padding: '1rem', textAlign: 'center' }}>Status</th>
                <th style={{ padding: '1rem', textAlign: 'center' }}>Bill</th>
                <th style={{ padding: '1rem', textAlign: 'center' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredBills.map(bill => {
                const dateStr = bill.createdAt ? new Date(bill.createdAt.toMillis()).toLocaleDateString() : 'N/A';
                const isPaid = bill.status === 'paid';
                const displayId = bill.id.substring(0, 8).toUpperCase();

                // Find the already-paid duplicate if it exists
                const paidDuplicate = !isPaid ? bills.find(b =>
                  b.id !== bill.id &&
                  b.status === 'paid' &&
                  b.requestId === bill.requestId &&
                  b.description.toLowerCase() === bill.description.toLowerCase() &&
                  b.amount === bill.amount
                ) : null;

                const isLikelyDuplicate = !!paidDuplicate;
                const originalPaidId = paidDuplicate ? paidDuplicate.id.substring(0, 8).toUpperCase() : null;

                return (
                  <tr key={bill.id} style={{ borderBottom: '1px solid var(--border-color)', backgroundColor: isLikelyDuplicate ? 'rgba(197, 34, 31, 0.04)' : 'transparent' }}>
                    <td style={{ padding: '1rem', fontFamily: 'monospace', color: 'var(--text-secondary)' }}>#{displayId}</td>
                    <td style={{ padding: '1rem', fontWeight: '500' }}>{bill.productName}</td>
                    <td style={{ padding: '1rem', color: 'var(--text-secondary)' }}>{bill.description}</td>
                    <td style={{ padding: '1rem', color: 'var(--text-secondary)' }}>{dateStr}</td>
                    <td style={{ padding: '1rem', textAlign: 'right', fontWeight: '600' }}>₹{Number(bill.amount).toFixed(2)}</td>
                    <td style={{ padding: '1rem', textAlign: 'center' }}>
                      <span style={{
                        display: 'inline-block',
                        padding: '0.25rem 0.75rem',
                        borderRadius: '9999px',
                        fontSize: '0.75rem',
                        fontWeight: '600',
                        border: '1px solid var(--border-color)',
                        color: isPaid ? 'var(--text-secondary)' : (isLikelyDuplicate ? 'var(--error-color)' : 'var(--text-primary)')
                      }}>
                        {isPaid ? 'PAID' : (isLikelyDuplicate ? 'DUPLICATE' : 'UNPAID')}
                      </span>
                    </td>
                    <td style={{ padding: '1rem', textAlign: 'center' }}>
                      <button
                        onClick={() => downloadBillPDF(bill)}
                        className="btn-primary"
                        style={{ padding: '0.4rem 0.9rem', margin: 0, minHeight: 'unset', fontSize: '0.8rem', display: 'inline-flex', alignItems: 'center', gap: '0.35rem', backgroundColor: 'transparent', color: 'var(--text-primary)' }}
                      >
                        <Download size={13} /> PDF
                      </button>
                    </td>
                    <td style={{ padding: '1rem', textAlign: 'center' }}>
                      {isPaid ? (
                        <span style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>Completed</span>
                      ) : isLikelyDuplicate ? (
                        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '0.25rem' }}>
                          <span style={{ color: 'var(--error-color)', fontSize: '0.75rem', fontWeight: '600' }}>
                            ⚠️ Already paid
                          </span>
                          <span style={{ color: 'var(--text-secondary)', fontSize: '0.7rem', fontFamily: 'monospace' }}>
                            Original: #{originalPaidId}
                          </span>
                        </div>
                      ) : (
                        <button
                          onClick={() => handlePay(bill.id)}
                          className="btn-primary"
                          style={{ padding: '0.5rem 1rem', margin: 0, minHeight: 'unset' }}
                        >
                          Pay Now
                        </button>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
