import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { db } from '../firebase';
import { collection, query, where, onSnapshot } from 'firebase/firestore';
import { Search, Download } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { RiskBadge, PageHeader } from './Guide';

export default function MyOrders() {
  const { currentUser } = useAuth();
  const navigate = useNavigate();
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    if (!currentUser) return;

    const q = query(
      collection(db, 'bills'),
      where('consumerId', '==', currentUser.uid)
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const fetched = [];
      snapshot.forEach((docSnap) => {
        fetched.push({ id: docSnap.id, ...docSnap.data() });
      });
      // Sort newest first
      fetched.sort((a, b) => b.createdAt?.toMillis() - a.createdAt?.toMillis());
      setBills(fetched);
      setLoading(false);
    }, (error) => {
      console.error("Error fetching bills:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [currentUser]);

  const handlePay = (billId) => {
    navigate(`/checkout/${billId}`);
  };

  const downloadBillPDF = (bill) => {
    const displayId = bill.id.substring(0, 8).toUpperCase();
    const dateStr = bill.createdAt ? new Date(bill.createdAt.toMillis()).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : 'N/A';
    const isPaid = bill.status === 'paid';

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8" />
        <title>Bill #${displayId}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 48px; color: #111; max-width: 560px; margin: 0 auto; }
          h1 { font-size: 1.75rem; margin-bottom: 0.25rem; }
          .sub { color: #666; font-size: 0.875rem; margin-bottom: 2rem; }
          table { width: 100%; border-collapse: collapse; margin-top: 1.5rem; }
          td { padding: 0.75rem 0; border-bottom: 1px solid #eee; }
          td:last-child { text-align: right; font-weight: 600; }
          .total td { border-top: 2px solid #111; border-bottom: none; font-weight: 700; font-size: 1.125rem; }
          .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.75rem; font-weight: 700; background: ${isPaid ? '#e6f4ea' : '#fce8e6'}; color: ${isPaid ? '#137333' : '#c5221f'}; }
          .footer { margin-top: 3rem; color: #999; font-size: 0.75rem; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Tether</h1>
        <p class="sub">Tax Invoice / Bill</p>
        <hr />
        <table>
          <tr><td>Bill ID</td><td>#${displayId}</td></tr>
          <tr><td>Product</td><td>${bill.productName}</td></tr>
          <tr><td>Description</td><td>${bill.description}</td></tr>
          <tr><td>Date</td><td>${dateStr}</td></tr>
          <tr><td>Status</td><td><span class="badge">${isPaid ? 'PAID' : 'UNPAID'}</span></td></tr>
          <tr class="total"><td>Total Amount</td><td>₹${Number(bill.amount).toFixed(2)}</td></tr>
        </table>
        <p class="footer">Generated by Tether &bull; ${new Date().toLocaleDateString()}</p>
      </body>
      </html>
    `;

    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); }, 400);
  };

  if (loading) {
    return <div className="page-container"><div className="empty-state"><span className="spinner" /></div></div>;
  }

  const filteredBills = bills.filter(bill => {
    if (!searchQuery.trim()) return true;
    const term = searchQuery.replace('#', '').trim().toUpperCase();
    return (
      bill.id.substring(0, 8).toUpperCase().includes(term) ||
      bill.productName?.toUpperCase().includes(term) ||
      bill.description?.toUpperCase().includes(term)
    );
  });

  const statusOf = (bill) =>
    bill.status === 'paid' ? { label: 'Paid', cls: 'paid' }
    : bill.status === 'rejected' ? { label: 'Rejected', cls: 'rejected' }
    : bill.reviewStatus === 'pending_review' ? { label: 'Needs review', cls: 'closed' }
    : { label: 'Unpaid', cls: 'unpaid' };

  return (
    <div className="page-container">
      <PageHeader
        title="Invoices"
        subtitle="Bills from your suppliers. Each one is checked by AI before you pay."
      />

      {bills.length > 0 && (
        <div className="search-field">
          <Search size={17} />
          <input
            type="text"
            className="form-input"
            placeholder="Search by ID, product or description"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
        </div>
      )}

      {bills.length === 0 ? (
        <div className="empty-state">No invoices yet. They appear here when a supplier bills you.</div>
      ) : filteredBills.length === 0 ? (
        <div className="empty-state">Nothing matches "{searchQuery}".</div>
      ) : (
        <div className="list">
          {filteredBills.map(bill => {
            const status = statusOf(bill);
            const dateStr = bill.createdAt ? new Date(bill.createdAt.toMillis()).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }) : '';
            const canPay = bill.status === 'unpaid';
            return (
              <div key={bill.id} className="list-row">
                <div className="list-main">
                  <div className="list-title">{bill.productName}</div>
                  <div className="list-sub">#{bill.id.substring(0, 8).toUpperCase()}{dateStr && ` · ${dateStr}`} · {bill.description}</div>
                </div>
                <div className="list-meta">
                  {bill.analysis && <RiskBadge analysis={bill.analysis} compact />}
                  <span className={`status-pill status-${status.cls}`}>{status.label}</span>
                  <span className="list-amount">₹{Number(bill.amount).toLocaleString('en-IN', { maximumFractionDigits: 2 })}</span>
                  <button className="btn-secondary btn-sm" onClick={() => downloadBillPDF(bill)} aria-label="Download PDF">
                    <Download size={14} /> PDF
                  </button>
                  {canPay && (
                    <button className="btn-primary btn-sm" style={{ marginTop: 0 }} onClick={() => handlePay(bill.id)}>
                      {bill.reviewStatus === 'pending_review' ? 'Review' : 'Pay'}
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
